default: &default
  adapter: postgresql
  encoding: unicode
  username: <%=ENV['DATABASE_USER']%>
  password: <%=ENV['DATABASE_PASSWORD']%>
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: testers_app_development

test:
  <<: *default
  database: testers_app_test

production:
  <<: *default
  database: testers_app_production
