default: &default
  adapter: postgresql
  encoding: unicode
  username: <%=ENV['DATABASE_USER']%>
  password: <%=ENV['DATABASE_PASSWORD']%>

development:
  <<: *default
  database: testers_app_development

test:
  <<: *default
  database: testers_app_test

production:
  <<: *default
  database: testers_app_production
